# .github/workflows/ci.yml
# GitHub Actions CI para projeto Maven + Cucumber HTML Report simples

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and run Cucumber tests
        run: mvn clean test --batch-mode

      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber-report
